version: '3.1'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: website
      MYSQL_USER: db_website
      MYSQL_PASSWORD: db_website_password
    networks:
      - site
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5589:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - site
  
  # PHP /w httpd
  # PHP extensions: mysqli, pdo, pdo_mysql
  web-server:
    depends_on:
      - db
    build:
      dockerfile: web-server.Dockerfile
      context: .
    ports:
      - 80:80
    restart: always
    volumes: 
      - './:/var/www/html'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: db_website
      MYSQL_PASSWORD: db_website_password
      MYSQL_DATABASE: website
    networks:
      - site
networks:
  site:
volumes:
  db_data:
